### ISSUE TITLE
Support ssh keys for authentication

### ISSUE THREAD

**Issue by crazed** [trigger/trigger#135]
Currently it looks like only password based authentication is supported and requires storing your data with tacas or gpg. I have an ssh public key rolled out and it would be great to simply rely on ssh-agent, grab ssh keys from default spots (~/.ssh/id_dsa, etc), or specify the ssh key file to use.

**Comment by jasonwilson18** [comment]
Please get this feature going! I need it!

**Comment by jathanism** [comment]
@jasonwilson18 Aww yeah.

**Comment by jasonwilson18** [comment]
This commit will change the digital landscape for years to come! Cultivate your brand and kick it out of the house when it turns 18!

**Comment by jathanism** [comment]
So... This is merged in. There isn't a way to specify the key to use yet. But we can add that later. 

@crazed please give this a whirl and let me know if you run into any issues!
