### ISSUE TITLE
SUPPORTED_PLATFORMS matching for generate/parse commands is case sensitive

### ISSUE THREAD

**Issue by crazed** [trigger/trigger#141]
Generally case sensitivity is great, but in this case I had a custom loader which set my device types to 'switch', 'firewall', 'router', etc. The default SUPPORTED_PLATFORMS variable is:

    SUPPORTED_PLATFORMS = {
        'a10': ['SWITCH'],
        'arista': ['SWITCH'],                         # Your "Cloud" network vendor
        'aruba': ['SWITCH'],                          # Wireless Controllers
        'brocade': ['ROUTER', 'SWITCH'],
        'cisco': ['ROUTER', 'SWITCH'],
        'citrix': ['SWITCH'],                         # Assumed to be NetScalers
        'dell': ['SWITCH'],
        'f5': ['LOAD BALANCING', 'SWITCH'],
        'force10': ['ROUTER', 'SWITCH'],
        'foundry': ['ROUTER', 'SWITCH'],
        'juniper': ['FIREWALL', 'ROUTER', 'SWITCH'],  # Any devices running Junos
        'mrv': ['CONSOLE SERVER', 'SWITCH'],
        'netscreen': ['FIREWALL'],                    # Pre-Juniper NetScreens
        'paloalto': ['FIREWALL'],
    } 

Which causes the code for `Commando._lookup_method` to fail to find any matching `to_`/`from_` functions. We should convert everything to either be `.lower()` or `.upper()` when doing this match

**Comment by jathanism** [comment]
This was actually fixed in 25bc2a6c9b0c835efd467087a2a07a57a5dba641 

Yay!
