### ISSUE TITLE
Cisco ASA support is not documented

### ISSUE THREAD

**Issue by jathanism** [trigger/trigger#211]
In the README and index page of the documentation, there is no mention of the Cisco ASA platform being supported.

**Comment by coxley** [comment]
Since I added that support, I *suppose* I should take this one. :)

The README doesn't currently list specific vendor support. Would be a good idea to have that as a point-of-reference

**Comment by jathanism** [comment]
You're right. The readme doesn't but the index page of the docs has the vendor section.

And also: own it!!

**Comment by coxley** [comment]
Since this is about supported platforms, is SRX supported?

**Comment by jathanism** [comment]
@coxley  SRX is supported because it's running JUNOS. In fact, this statement should be updated because I did do some work last summer on clarifying this relationship to officially support Juniper firewall devices running JUNOS *or* ScreenOS. Check out [`trigger.netdevices.NetDevice.is_netscreen()`](https://github.com/trigger/trigger/blob/develop/trigger/netdevices/__init__.py#L535)

**Comment by coxley** [comment]
@jathanism: Did #211 satisfy this issue?
