### ISSUE TITLE
TextFSM

### ISSUE THREAD

**Issue by chepazzo** [trigger/trigger#220]
See: https://code.google.com/p/textfsm/wiki/TextFSMHowto

This would be a great addition to Trigger:

The ability to specify, in settings, a textfsm template dir that contains templates for known commands. Then, if trigger is run with a 'structured-data' option, it will look in that dir, apply an appropriate template, and return structured data.

example:  http://jedelman.com/home/programmatic-access-to-cli-devices-with-textfsm/

**Comment by jathanism** [comment]
Verrry interesting. I shall consume this and provide meaningful comments!

**Comment by tcuthbert** [comment]
#249 This has now been implemented.
