### ISSUE TITLE
gong's .gorc not working for Arista and Juniper devices

### ISSUE THREAD

**Issue by teomcpy** [trigger/trigger#258]
Trying to use gong with the Arista vEOS and Juniper JunOS. Currently, the tool seems to work only on Cisco devices.

This is the .gorc file:

_juniper:
    set cli timestamp
    show interfaces terse
    show system users

cisco:
    show clock
    show ip interface brief
    terminal width 132

arista:
    show clock
    show uptime
    show ip interface brief

foundry:
    show clock_

When running gong on this device:

ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#06$ gong 172.16.1.4
_Connecting to 172.16.1.4.  Use ^X to exit.

Fetching credentials from /home/ubuntu/.tacacsrc
Last login: Fri Mar 25 13:34:28 2016 from 172.16.1.1
localhost#
localhost#
localhost#_

A few times, it also appeared like this:

ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#06$ gong 172.16.1.4
_Connecting to 172.16.1.4.  Use ^X to exit.

Fetching credentials from /home/ubuntu/.tacacsrc
Last login: Fri Mar 25 13:34:28 2016 from 172.16.1.1
**show clock
show uptime
show ip interface brief**
localhost#
localhost#
localhost#_

Now, for Juniper, again, nothing is shown - commands are not executed:

gong 172.16.1.3
Connecting to 172.16.1.3.  Use ^X to exit.

Fetching credentials from /home/ubuntu/.tacacsrc
--- JUNOS 10.2R3.10 built 2010-10-16 20:36:59 UTC
mihai1@abcd>

**Comment by jathanism** [comment]
This is a bug in the documentation. The `.gorc` file should start with an `[init_commands]` section, so your file should look like this:

```
[init_commands]
_juniper:
    set cli timestamp
    show interfaces terse
    show system users

cisco:
    show clock
    show ip interface brief
    terminal width 132

arista:
    show clock
    show uptime
    show ip interface brief

foundry:
    show clock_
```

Thanks for catching this.

**Comment by jathanism** [comment]
Hm. Looks like there's also a bug with the commands being sent out of order, too. I'm investigating that as well.

**Comment by teomcpy** [comment]
Thank you so much for your support!

**Comment by teomcpy** [comment]
Ok, I already had [init_commands] at the top of the file, before all the comments. I have deleted the comments and I now have this in the file:

_[init_commands]
juniper:
    set cli timestamp
    show interfaces terse
    show system users

cisco:
    show clock
    show ip interface brief
    terminal width 132

arista:
    show clock
    show uptime
    show ip interface brief

foundry:
    show clock_

However, after trying again on my Arista vEOS:

First try:

**gong 172.16.1.4
Connecting to 172.16.1.4.  Use ^X to exit.

Fetching credentials from /home/ubuntu/.tacacsrc
^[[0nlocalhost#n**


Second try:

**gong 172.16.1.4
Connecting to 172.16.1.4.  Use ^X to exit.

Fetching credentials from /home/ubuntu/.tacacsrc
Last login: Tue Mar 29 06:55:29 2016 from 172.16.1.1
show clock

show uptime

show ip interface brief

show clock

show uptime

show ip interface brief

localhost#**


Third try - same results as in the second try.

**Comment by jathanism** [comment]
Ok, narrowing it down to Arista helps. Thanks!
