### ISSUE TITLE
Bad hostname validation

### ISSUE THREAD

**Issue by johnfzc** [trigger/trigger#266]
Trigger attempts to validate hostname's before pinging them, it ignores names that don't match the regex rather than leaving it up to the system. The filtering is performed by `VALID_HOST_RE` in `trigger/utils/network.py`.

**Comment by jathanism** [comment]
When this was originally added about 2 years ago, it was to hide errors from stderr. We should take the opportunity to change this to use `subprocess.check_call()` instead of `commands.getstatusoutput()` which is deprecated anyhow! :)

**Comment by jathanism** [comment]
Fixed in #267, but not really. #271 is going to try to address it. FYI @johnfzc

**Comment by johnfzc** [comment]
#271 fixes the new bug this introduced, #280 added documentation.
