### ISSUE TITLE
utils/network.py: fd not closed properly

### ISSUE THREAD

**Issue by supertylerc** [trigger/trigger#271]
Minor bug introduced by #267.  [These lines](https://github.com/johnfzc/trigger/blob/71d6d5432aed68585623f283a871910fa2654b2d/trigger/utils/network.py#L46-L55) redirect output to `os.devnull`, but the fd isn't properly closed.  Here's an example of the issue on OS X.

### Example Python Script

```python
#!/usr/bin/env python2
import subprocess
x = open('/dev/null', 'w')
subprocess.call(['ls'], stdout=x, stderr=x, close_fds=True)
input('go check the fd!')
```

### Verifying the Bug

```
$ python harbl.py

# In a separate terminal:
$ ps -p $(lsof /dev/null | grep python | awk '{print $2}')
  PID TTY           TIME CMD
35608 ttys005    0:00.02 python harbl.py
```

### Fixing the Bug

To fix the issue, either `try/finally` needs to be used or (preferably) a context manager, similar to below:

```python
#!/usr/bin/env python2
import subprocess
with open('/dev/null', 'w') as f:
    subprocess.call(['ls'], stdout=f, stderr=f, close_fds=True)
input('go check the fd!')
```

And validating:

```
$ python harbl.py
check the fd!

# In a separate terminal:
$ lsof /dev/null | grep python
$
```

I could submit the PR to correct this.

**Comment by jathanism** [comment]
Well that's no good. The context manager is certainly a better approach. Good thing you're catching this before we released it. ;-)

**Comment by supertylerc** [comment]
Thanks. I'll submit the PR in an hour or two. Out and about for a bit! :)
