### ISSUE TITLE
`gnng` should support partial hostname lookups like `gong` does

### ISSUE THREAD

**Issue by jathanism** [trigger/trigger#89]
This should not happen:

    % gnng device
    Traceback (most recent call last):
      File "/opt/bin/gnng", line 454, in <module>
        main()
      File "/opt/bin/gnng", line 438, in main
        routers = fetch_router_list(args[1:])
      File "/opt/bin/gnng", line 91, in fetch_router_list
        if not pass_filters(nd.find(arg)):
      File "/opt/lib/python2.7/site-packages/trigger/netdevices/__init__.py", line 718, in find
        raise KeyError(key)
    KeyError: 'device'

**Comment by supertylerc** [comment]
Is #278 actually a duplicate?  This issue seems to be for partial hostname lookups (which is already a thing) whereas #278 is for a graceful failure if the device just doesn't exist.

**Comment by jathanism** [comment]
Ah sorry, so it's the same underlying machinery. It's the "look up a device and if it's not found either fail gracefully or try to present a list of closest matches" problem.

**Comment by supertylerc** [comment]
Thanks.  I think I have a fix.  Looks like this now:

```
$ gnng 10.254.254.2 10.254.254.3
Device not found: 10.254.254.3
DEVICE: 10.254.254.2
Interface       | Addresses    | Subnets         | ACLs IN | ACLs OUT | Description
-----------------------------------------------------------------------------------
    Ethernet0/0 | 10.254.254.2 | 10.254.254.0/24 |         |          |  harbl
$
```
